version: '3.8'

services:
  # Container Aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surat-app_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/entrypoint.sh:/entrypoint.sh
      - /app/vendor
    entrypoint: ["sh", "/entrypoint.sh"]
    networks:
      - surat-app_network

  # Container Web Server Nginx
  nginx:
    image: nginx:1.21-alpine
    container_name: surat-app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - surat-app_network

  # Container Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: surat-app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - surat-app_db_data:/var/lib/postgresql/data
    networks:
      - surat-app_network

networks:
  surat-app_network:
    driver: bridge

volumes:
  surat-app_db_data:
    driver: local

# services:
#     laravel.test:
#         build:
#             context: './vendor/laravel/sail/runtimes/8.4'
#             dockerfile: Dockerfile
#             args:
#                 WWWGROUP: '${WWWGROUP}'
#         image: 'sail-8.4/app'
#         extra_hosts:
#             - 'host.docker.internal:host-gateway'
#         ports:
#             - '${APP_PORT:-80}:80'
#             - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
#         environment:
#             WWWUSER: '${WWWUSER}'
#             LARAVEL_SAIL: 1
#             XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#             XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
#             IGNITION_LOCAL_SITES_PATH: '${PWD}'
#         volumes:
#             - '.:/var/www/html'
#         networks:
#             - sail
#         depends_on:
#             - pgsql
#     pgsql:
#         image: 'postgres:17-alpine'
#         ports:
#             - '${FORWARD_DB_PORT:-5432}:5432'
#         environment:
#             PGPASSWORD: '${DB_PASSWORD:-secret}'
#             POSTGRES_DB: '${DB_DATABASE}'
#             POSTGRES_USER: '${DB_USERNAME}'
#             POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
#         volumes:
#             - 'sail-pgsql:/var/lib/postgresql/data'
#             - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
#         networks:
#             - sail
#         healthcheck:
#             test:
#                 - CMD
#                 - pg_isready
#                 - '-q'
#                 - '-d'
#                 - '${DB_DATABASE}'
#                 - '-U'
#                 - '${DB_USERNAME}'
#             retries: 3
#             timeout: 5s
# networks:
#     sail:
#         driver: bridge
# volumes:
#     sail-pgsql:
#         driver: local